spring:
  application:
    name: authService

  datasource:
    url: jdbc:mysql://localhost:3306/lingchat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true # 格式化sql语句
          dialect: org.hibernate.dialect.MySQLDialect # 适配 MySQL 8+ 版本，向下兼容以前的版本

  server:
    port: 8080

